#[derive(Copy, Clone)]
#[repr(C)]
pub struct TripletEncoding {
    pub byteCount: ::core::ffi::c_uint,
    pub xBits: ::core::ffi::c_uint,
    pub yBits: ::core::ffi::c_uint,
    pub deltaX: ::core::ffi::c_uint,
    pub deltaY: ::core::ffi::c_uint,
    pub xSign: ::core::ffi::c_int,
    pub ySign: ::core::ffi::c_int,
}
#[no_mangle]
pub static mut tripletEncodings: [TripletEncoding; 128] = [
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 256 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 256 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 512 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 512 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 768 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 768 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 1024 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 0 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 1024 as ::core::ffi::c_uint,
        xSign: 0 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 256 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 256 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 512 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 512 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 768 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 768 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 1024 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 0 as ::core::ffi::c_uint,
        deltaX: 1024 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 0 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 17 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 33 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 17 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 33 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 2 as ::core::ffi::c_uint,
        xBits: 4 as ::core::ffi::c_uint,
        yBits: 4 as ::core::ffi::c_uint,
        deltaX: 49 as ::core::ffi::c_uint,
        deltaY: 49 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 1 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 257 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 1 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 257 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 3 as ::core::ffi::c_uint,
        xBits: 8 as ::core::ffi::c_uint,
        yBits: 8 as ::core::ffi::c_uint,
        deltaX: 513 as ::core::ffi::c_uint,
        deltaY: 513 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 4 as ::core::ffi::c_uint,
        xBits: 12 as ::core::ffi::c_uint,
        yBits: 12 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 4 as ::core::ffi::c_uint,
        xBits: 12 as ::core::ffi::c_uint,
        yBits: 12 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 4 as ::core::ffi::c_uint,
        xBits: 12 as ::core::ffi::c_uint,
        yBits: 12 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 4 as ::core::ffi::c_uint,
        xBits: 12 as ::core::ffi::c_uint,
        yBits: 12 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 5 as ::core::ffi::c_uint,
        xBits: 16 as ::core::ffi::c_uint,
        yBits: 16 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 5 as ::core::ffi::c_uint,
        xBits: 16 as ::core::ffi::c_uint,
        yBits: 16 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: -(1 as ::core::ffi::c_int),
    },
    TripletEncoding {
        byteCount: 5 as ::core::ffi::c_uint,
        xBits: 16 as ::core::ffi::c_uint,
        yBits: 16 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: -(1 as ::core::ffi::c_int),
        ySign: 1 as ::core::ffi::c_int,
    },
    TripletEncoding {
        byteCount: 5 as ::core::ffi::c_uint,
        xBits: 16 as ::core::ffi::c_uint,
        yBits: 16 as ::core::ffi::c_uint,
        deltaX: 0 as ::core::ffi::c_uint,
        deltaY: 0 as ::core::ffi::c_uint,
        xSign: 1 as ::core::ffi::c_int,
        ySign: 1 as ::core::ffi::c_int,
    },
];
