#[derive(Copy, Clone)]
pub struct TripletEncoding {
    pub byteCount: u32,
    pub xBits: u32,
    pub yBits: u32,
    pub deltaX: u32,
    pub deltaY: u32,
    pub xSign: i32,
    pub ySign: i32,
}

pub static tripletEncodings: [TripletEncoding; 128] = [
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 0,
        xSign: 0,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 0,
        xSign: 0,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 256,
        xSign: 0,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 256,
        xSign: 0,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 512,
        xSign: 0,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 512,
        xSign: 0,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 768,
        xSign: 0,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 768,
        xSign: 0,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 1024,
        xSign: 0,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 0,
        yBits: 8,
        deltaX: 0,
        deltaY: 1024,
        xSign: 0,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 0,
        deltaY: 0,
        xSign: -1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 0,
        deltaY: 0,
        xSign: 1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 256,
        deltaY: 0,
        xSign: -1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 256,
        deltaY: 0,
        xSign: 1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 512,
        deltaY: 0,
        xSign: -1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 512,
        deltaY: 0,
        xSign: 1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 768,
        deltaY: 0,
        xSign: -1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 768,
        deltaY: 0,
        xSign: 1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 1024,
        deltaY: 0,
        xSign: -1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 8,
        yBits: 0,
        deltaX: 1024,
        deltaY: 0,
        xSign: 1,
        ySign: 0,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 17,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 17,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 17,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 17,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 33,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 33,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 33,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 33,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 49,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 49,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 49,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 1,
        deltaY: 49,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 17,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 17,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 17,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 17,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 33,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 33,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 33,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 33,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 49,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 49,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 49,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 17,
        deltaY: 49,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 17,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 17,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 17,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 17,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 33,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 33,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 33,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 33,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 49,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 49,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 49,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 33,
        deltaY: 49,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 17,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 17,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 17,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 17,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 33,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 33,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 33,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 33,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 49,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 49,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 49,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 2,
        xBits: 4,
        yBits: 4,
        deltaX: 49,
        deltaY: 49,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 257,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 257,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 257,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 257,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 513,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 513,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 513,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 1,
        deltaY: 513,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 257,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 257,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 257,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 257,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 513,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 513,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 513,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 257,
        deltaY: 513,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 1,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 1,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 1,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 1,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 257,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 257,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 257,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 257,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 513,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 513,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 513,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 3,
        xBits: 8,
        yBits: 8,
        deltaX: 513,
        deltaY: 513,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 4,
        xBits: 12,
        yBits: 12,
        deltaX: 0,
        deltaY: 0,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 4,
        xBits: 12,
        yBits: 12,
        deltaX: 0,
        deltaY: 0,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 4,
        xBits: 12,
        yBits: 12,
        deltaX: 0,
        deltaY: 0,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 4,
        xBits: 12,
        yBits: 12,
        deltaX: 0,
        deltaY: 0,
        xSign: 1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 5,
        xBits: 16,
        yBits: 16,
        deltaX: 0,
        deltaY: 0,
        xSign: -1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 5,
        xBits: 16,
        yBits: 16,
        deltaX: 0,
        deltaY: 0,
        xSign: 1,
        ySign: -1,
    },
    TripletEncoding {
        byteCount: 5,
        xBits: 16,
        yBits: 16,
        deltaX: 0,
        deltaY: 0,
        xSign: -1,
        ySign: 1,
    },
    TripletEncoding {
        byteCount: 5,
        xBits: 16,
        yBits: 16,
        deltaX: 0,
        deltaY: 0,
        xSign: 1,
        ySign: 1,
    },
];
